# Generated by Django 4.1.3 on 2022-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='default/ak47.jpg', upload_to='images/'),
        ),
    ]
